get_forecasts_extra:
  target:
    entity:
      domain: weather
  fields:
    type:
      required: true
      selector:
        select:
          options:
            - "hourly"
            - "twice_daily"
          translation_key: nws_forecast_type
